name: 'Build Warp'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.7 # Cairo was tested with this version

    - name: Gen Cache Id
      run: |
        echo "::set-output name=timestamp::$(date '+%s')"
      id: cache-id
      shell: sh

    - name: Cache poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ steps.cache-id.outputs.timestamp }}
        restore-keys: |
          poetry-cache-

    - name: Install dependencies
      run: >
        sudo add-apt-repository ppa:ethereum/ethereum

        sudo add-apt-repository 'deb http://mirrors.kernel.org/ubuntu hirsute main universe'

        sudo apt-get -y install gcc-11 g++-11 solc
        libboost-filesystem-dev libboost-system-dev
        libboost-program-options-dev

        curl -sSL https://install.python-poetry.org | python3
      shell: sh

    - name: Install Warp
      run: make
      shell: sh
